[aws]
default_region = "us-east-2"
default_bucket_name = "databridge-s3-storage"

[mongodb]
database_name = "DataBridgeTest"
documents_collection = "documents"
chunks_collection = "document_chunks"

[mongodb.vector]
dimensions = 1536
index_name = "vector_index"

[model]
embedding_model = "text-embedding-3-small"
completion_model = "gpt-3.5-turbo"

[document_processing]
chunk_size = 1000
chunk_overlap = 200
default_k = 4

[video_processing]
frame_sample_rate = 120

[server]
host = "localhost"
port = 8000
reload = false

[auth]
jwt_algorithm = "HS256"