morphik-host = "api.morphik.ai"

# EE-specific configurations

[google_drive]
redirect_uri = "https://api.morphik.ai/ee/connectors/google_drive/oauth2callback" # Must match GCP console setting
scopes = [
    "https://www.googleapis.com/auth/drive.readonly"
    # Add other scopes as needed, e.g.:
    # "https://www.googleapis.com/auth/drive.metadata.readonly"
]
token_storage_path = "ee_tokens" # Default path within the application for storing tokens, ensure this directory is gitignored if created locally.
